# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c06c8b1d4ceb2d0576d476cdf72cf50000252a4156e7394b988ff02224d550a26478677a8d21f0ffe5d62aebd953ab786c05277e5f0400bb7195059b56b8bd61

test:
  secret_key_base: df5d49fe746ed421072b4ef21c946a7940d50ab6c5cf48e6230e0e66a01afbe1598e66f793ab0ab737a7542f5cee892d0d066264515788e73b89e2a6dd4e3799

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
